// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WorkspaceFiles
{
    internal sealed partial class Vsix
    {
        public const string Id = "WorkspaceFiles.e5308ac4-ca47-4992-945b-9b144a10c2d0";
        public const string Name = "Workspace Files";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
