// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WorkspaceFiles
{
    internal sealed partial class Vsix
    {
        public const string Id = "WorkspaceFiles.e5308ac4-ca47-4992-945b-9b144a10c2d0";
        public const string Name = "Workspace Browser";
        public const string Description = @"Gives access to all files and folders from the file system under the repo- or solution root folder. All in the same Solution Explorer view.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "files, folders, repo, root";
    }
}
