// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WorkspaceFiles
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string WorkspaceFilesString = "d428d0a0-b960-4617-a7fd-15743d49e72e";
        public static Guid WorkspaceFiles = new Guid(WorkspaceFilesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int RootContextMenu = 0x0001;
        public const int FileContextMenu = 0x0002;
        public const int FolderContextMenu = 0x0003;
        public const int RootContextMenuGroup = 0x0010;
        public const int FileContextMenuGroup = 0x0020;
        public const int FolderContextMenuGroup = 0x0030;
        public const int SettingsGroup = 0x0040;
        public const int SolutionToolbarGroup = 0x0050;
        public const int Settings = 0x0100;
        public const int Delete = 0x0200;
        public const int OpenInExplorer = 0x0300;
        public const int ToggleWorkspace = 0x0400;
    }
}