// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WorkspaceFiles
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string WorkspaceFilesString = "d428d0a0-b960-4617-a7fd-15743d49e72e";
        public static Guid WorkspaceFiles = new Guid(WorkspaceFilesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int RootContextMenu = 0x0001;
        public const int FileContextMenu = 0x0002;
        public const int FolderContextMenu = 0x0003;
        public const int RootContextMenuGroup = 0x0010;
        public const int FileContextMenuGroup = 0x0020;
        public const int FolderContextMenuGroup = 0x0030;
        public const int FileOpenGroup = 0x0040;
        public const int FolderOpenGroup = 0x0041;
        public const int RootOpenGroup = 0x0042;
        public const int SolutionToolbarGroup = 0x0050;
        public const int FileOperationsGroup = 0x0060;
        public const int FolderOperationsGroup = 0x0061;
        public const int RootOperationsGroup = 0x0062;
        public const int AddItemGroup = 0x0070;
        public const int Delete = 0x0200;
        public const int OpenInExplorer = 0x0300;
        public const int ToggleWorkspace = 0x0400;
        public const int CopyFullPath = 0x0500;
        public const int OpenInDefaultProgram = 0x0600;
        public const int Rename = 0x0700;
        public const int AddFolder = 0x0800;
        public const int RemoveFolder = 0x0900;
        public const int NewFolder = 0x1000;
        public const int NewFile = 0x1001;
        public const int OpenInVsCode = 0x1002;
    }
}